### ISSUE TITLE
F3 Compatibility with servers to get the green checkmark

### ISSUE THREAD

**Issue by zachsai** [cominixo/BetterF3#23] opened 2021-04-30 20:51 UTC
Could you optimize the mod so if its on a server it doesnt prevent the server from loading? I ask this because it helps with the green checkmark next to servers for modpack developers :)

**Comment by cominixo** [comment] 2021-04-30 20:55
Duplicate of #21, already fixed in the Forge fork (https://github.com/TreyRuffy/BetterF3/issues/3).

**Closed as completed by cominixo** 2021-04-30 20:55 UTC
