### ISSUE TITLE
Font Scale option doesn't scale FPS/TPS boxes correctly

### ISSUE THREAD

**Issue by JumperREDACTED** [cominixo/BetterF3#45] opened 2021-09-16 13:47 UTC
![image](https://user-images.githubusercontent.com/83337894/133623525-00c2b8c0-448c-443a-a983-5a00c88e307d.png)

**Comment by cominixo** [comment] 2021-09-16 13:50
Duplicate of #27

**Closed as completed by cominixo** 2021-09-16 13:50 UTC
