### ISSUE TITLE
Delete/Edit Module stay active after using Delete Module and cause CtD

### ISSUE THREAD

**Issue by bidaumm** [cominixo/BetterF3#38] opened 2021-07-24 03:28 UTC
If you delete a module in the F3+M menu the buttons for delete/edit stay active but you dont have any module selected. 
If you then hit one of them again without selecting another module the game crashes to desktop

**Comment by cominixo** [comment] 2021-07-24 20:39
Duplicate of #34

**Closed as completed by cominixo** 2021-07-24 20:39 UTC
