### ISSUE TITLE
[Bug] Incompatibility with LambaControls

### ISSUE THREAD

**Issue by ZaneDragonBorn** [cominixo/BetterF3#11] opened 2021-01-19 01:25 UTC
Seems to be a Crash on Launch with LambaControls and this mod both installed. The easiest solution is to uninstall this mod, but I like it so... You Know.
[crash-2021-01-18_20.20.39-server.txt](https://github.com/cominixo/BetterF3/files/5833033/crash-2021-01-18_20.20.39-server.txt)

**Comment by cominixo** [comment] 2021-01-19 01:44
Duplicate of #4 , I plan to fix this soon, don't have access to a computer for a couple weeks so it might take a bit.

**Closed as completed by cominixo** 2021-01-19 01:44 UTC
