### ISSUE TITLE
FPS Caps To 60 On Gui Show

### ISSUE THREAD

**Issue by ghost** [cominixo/BetterF3#51] opened 2021-12-04 02:44 UTC
When I open the F3 menu, I can see the FPS drop from whatever its "true value" is to ~60FPS. This happens regardless of my vsync settings.

**Comment by cominixo** [comment] 2021-12-04 15:48
Duplicate of #5

**Closed as completed by cominixo** 2021-12-04 15:48 UTC

**Comment by ghost** [comment] 2021-12-05 13:20
Oh, apologies! Didn't see that (I did search!).
