### ISSUE TITLE
[Bug]: BetterF3 mod not coloring debug menu, also debug menu becoming stuck on screen

### ISSUE THREAD

**Issue by Gamemassa** [cominixo/BetterF3#96] opened 2022-07-09 23:13 UTC
### Describe the Bug

I don't get any crashes or error messages when I load the latest version of Forge with BetterF3 (as I have been with other mods that broke recently), but when I load into my worlds and press F3, the debug menu is not colorized as it's supposed to be, and it also does not go away when I press F3 again, so it remains on my screen until I disconnect from my worlds.

Additional note: this appears to be happening on both my singleplayer worlds and on multiplayer servers (not sure if any difference would be expected, but point is I'm not seeing any).

### Steps to Reproduce

Enter an SP world or an MP server and press F3.

### Expected Behavior

Debug menu comes up but is not colored. Debug menu also not disappearing on subsequent F3 presses.

### Screenshots

![image](https://user-images.githubusercontent.com/18667108/178125337-bfa88f4f-731a-4162-b09f-fdc67876e444.png)

### Modloader Type

Minecraft Forge

### Modloader Version

41.0.85

### Mod Version

1.3.1

**Comment by Monorange** [comment] 2022-07-13 02:27
Try going into settings and in General Settings turn "Disable Mod"  to "No"

**Comment by TreyRuffy** [comment] 2022-07-19 07:41
Closed do to probable duplicate of #99.

**Closed as completed by TreyRuffy** 2022-07-19 07:41 UTC
